version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.12

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-npm-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-npm-dependencies-{{ checksum "package-lock.json" }}

      # run tests!
      - run: npm run build

